### ISSUE TITLE
Can't seem to read from python's lz4

### ISSUE THREAD

**Issue by gappleto97** [pierrec/node-lz4#48]
[Python's lz4](https://github.com/python-lz4/python-lz4) produces this when compressing 'a':

`<Buffer 01 00 00 00 10 61>`

Your library produces this when compressing 'a':

`<Buffer 04 22 4d 18 64 70 b9 02 00 00 00 10 61 00 00 00 00 56 74 0d 55>`

Neither library can decode the other's output. Is there any chance you could try to make these libraries compatible, since both are supposed to use the same compression?

See: https://github.com/python-lz4/python-lz4/issues/8

**Comment by pierrec** [comment]
Yes this is due to the fact that the Python library does not implement the LZ4 stream format, only the block format, which this version does. See the Python README Introduction section.

However, the Node version does expose the functions to encode/decode lz4 blocks. See decodeBlock() and encodeBlock().

I would discourage using them and only use the stream format as this is the officially supported format for LZ4.

**Comment by gappleto97** [comment]
@jonathanunderwood says that they're using frames, not blocks. I tried using your utility functions, but the python lz4 module didn't understand the block format either.

**Comment by jonathanunderwood** [comment]
That's not what I said. :)

**Comment by gappleto97** [comment]
Ah, sorry. I misunderstood.

**Comment by jonathanunderwood** [comment]
As I mentioned in the other ticket - the format that's really designed for compatibility across implementations is the frame format:

https://github.com/lz4/lz4/wiki/lz4_Frame_format.md

the python-lz4 library now supports that, and I'll make a release over the xmas period.

**Comment by pierrec** [comment]
Closing this as it is not a node-lz4 issue.
